export interface Airport {
  icao: string
  name: string
  state: string
  restaurant: {
    name: string
    description: string
    placeId?: string
    website?: string
  }
  lat: number
  lng: number
  elevation?: number                              // feet MSL
  fuel?: "100LL" | "Jet-A" | "both" | "none"
  hours?: string                                  // restaurant hours, not airport hours
  runwaySurface?: "asphalt" | "grass" | "concrete"
}

export const airports: Airport[] = [
  // California
  {
    icao: "KCMA",
    name: "Camarillo Airport",
    state: "CA",
    restaurant: {
      name: "Waypoint Cafe",
      description: "Popular SoCal fly-in destination with excellent breakfast and lunch.",
      placeId: "ChIJ51cOKpFJ6IAR1yenlNwQQSw",
      website: "https://www.waypointcafe.com",
    },
    lat: 34.2137,
    lng: -119.0943,
    elevation: 77,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KSZP",
    name: "Santa Paula Airport",
    state: "CA",
    restaurant: {
      name: "The Flying Spoon",
      description: "Charming cafe at a historic aviation community airport.",
      placeId: "ChIJsdo0BBW16YARPGiBo4fTET4",
    },
    lat: 34.3472,
    lng: -119.0612,
    elevation: 243,
    fuel: "100LL",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KAVX",
    name: "Catalina Airport",
    state: "CA",
    restaurant: {
      name: "Airport in the Sky Restaurant",
      description: "Legendary hilltop restaurant on Santa Catalina Island. The flight alone is worth it.",
      placeId: "ChIJz5si5J5v3YARkt-Ky_4dfp8",
      website: "https://www.visitcatalinaisland.com",
    },
    lat: 33.4049,
    lng: -118.4165,
    elevation: 1602,
    fuel: "100LL",
    hours: "Daily · 8am–4pm",
    runwaySurface: "asphalt",
  },
  {
    icao: "KMYF",
    name: "Montgomery-Gibbs Executive Airport",
    state: "CA",
    restaurant: {
      name: "94th Aero Squadron",
      description: "WWII-themed restaurant and a beloved San Diego institution since 1974.",
      placeId: "ChIJzYIHtKT_24ARXYWXYzHMjJQ",
      website: "https://www.94thaero.com",
    },
    lat: 32.8157,
    lng: -117.1396,
    elevation: 427,
    fuel: "both",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },
  {
    icao: "KHAF",
    name: "Half Moon Bay Airport",
    state: "CA",
    restaurant: {
      name: "Pilot Light",
      description: "Bright, modern cafe steps from the ramp with coastal fog views and creative breakfast and lunch dishes. A local favorite at one of the Bay Area's most scenic fly-in airports.",
      placeId: "ChIJy48wjYdzj4ARzRaL2nOs3vM",
      website: "https://pilotlightcafe.com/",
    },
    lat: 37.5134,
    lng: -122.5009,
    elevation: 66,
    fuel: "100LL",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KSQL",
    name: "San Carlos Airport",
    state: "CA",
    restaurant: {
      name: "SkyKitchen",
      description: "Beloved Bay Area institution on the San Carlos ramp serving hearty breakfasts and lunches with a front-row view of one of the busiest GA airports in California.",
      placeId: "ChIJn6yuqwmij4ARrdscqJxK_II",
    },
    lat: 37.5151,
    lng: -122.2504,
    elevation: 7,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KTRK",
    name: "Truckee Tahoe Airport",
    state: "CA",
    restaurant: {
      name: "Red Truck",
      description: "Casual mountain eatery at 5,900 ft serving après-ski comfort food, craft burgers, and cold beers. Park on the ramp and walk straight in — stunning Sierra Nevada backdrop included.",
      placeId: "ChIJJ_USK81hmYAR2TCb91hi6SQ",
      website: "http://redtrucktahoe.com/",
    },
    lat: 39.3195,
    lng: -120.1450,
    elevation: 5900,
    fuel: "both",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },
  {
    icao: "KFUL",
    name: "Fullerton Municipal Airport",
    state: "CA",
    restaurant: {
      name: "Wings Cafe",
      description: "Classic SoCal fly-in hangout on the Fullerton ramp with a menu full of breakfast staples and pilot-friendly portions. A fixture of the Southern California GA community.",
      placeId: "ChIJZ60yw7Yr3YAR4WAwNhA1my0",
    },
    lat: 33.8705,
    lng: -117.9796,
    elevation: 96,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  // Arizona
  {
    icao: "KSEZ",
    name: "Sedona Airport",
    state: "AZ",
    restaurant: {
      name: "Mesa Grill",
      description: "Perched atop Airport Mesa with jaw-dropping red rock views in every direction.",
      placeId: "ChIJTUgkR8umLYcReX_a7wyurvg",
      website: "https://www.mesagrilledona.com",
    },
    lat: 34.8486,
    lng: -111.7885,
    elevation: 4827,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  // Florida
  {
    icao: "KCEW",
    name: "Bob Sikes Airport",
    state: "FL",
    restaurant: {
      name: "Stick & Rudder",
      description: "Classic $100 hamburger spot right next to the ramp.",
      placeId: "ChIJB4XvpeV1kYgR6NuND9BiMQY",
    },
    lat: 30.7789,
    lng: -86.5221,
    elevation: 235,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KSPG",
    name: "Albert Whitted Airport",
    state: "FL",
    restaurant: {
      name: "The Hangar Restaurant & Flight Lounge",
      description: "Waterfront dining on Tampa Bay with seaplane activity and stunning sunsets.",
      placeId: "ChIJTUtvaZrhwogRSkZnTR1DnR8",
      website: "https://www.hangarstpete.com",
    },
    lat: 27.7658,
    lng: -82.6268,
    elevation: 7,
    fuel: "100LL",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },
  {
    icao: "KLAL",
    name: "Lakeland Linder International",
    state: "FL",
    restaurant: {
      name: "Sora Eatery",
      description: "Upstairs at the terminal with runway views — home of Sun 'n Fun and great food year-round.",
      placeId: "ChIJTVWkLaI53YgRJLdDS9WFH1M",
    },
    lat: 27.9889,
    lng: -82.0186,
    elevation: 142,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  // Maryland
  {
    icao: "KGAI",
    name: "Montgomery County Airpark",
    state: "MD",
    restaurant: {
      name: "Café Sophie",
      description: "Upstairs in the terminal building — friendly counter-service spot beloved by the local GA community.",
      placeId: "ChIJ2a_7HTHTt4kR3tKgiYJpTkk",
    },
    lat: 39.1684,
    lng: -77.1660,
    elevation: 539,
    fuel: "100LL",
    hours: "Mon–Fri · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KFDK",
    name: "Frederick Municipal Airport",
    state: "MD",
    restaurant: {
      name: "Airways Inn of Frederick",
      description: "On-field restaurant at Frederick Municipal serving breakfast, lunch, and dinner with views of the active runway — a Mid-Atlantic pilots' classic.",
      placeId: "ChIJ6-LnboDayYkRZpSo9o-TlrI",
      website: "https://www.airwaysinnoffrederick.com",
    },
    lat: 39.4176,
    lng: -77.3742,
    elevation: 303,
    fuel: "both",
    hours: "Daily · breakfast through dinner",
    runwaySurface: "asphalt",
  },
  // California
  {
    icao: "KSBP",
    name: "San Luis Obispo County Regional Airport",
    state: "CA",
    restaurant: {
      name: "Spirit of San Luis Restaurant",
      description: "Legendary Central California fly-in with ocean breezes and a front porch view of the ramp.",
      placeId: "ChIJr0US8bj27IARj2KF4cRaXWI",
    },
    lat: 35.2368,
    lng: -120.6426,
    elevation: 212,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  // Florida
  {
    icao: "KSGJ",
    name: "Northeast Florida Regional Airport",
    state: "FL",
    restaurant: {
      name: "Hangar One Bistro Eatery & Bar",
      description: "On-field bistro at St. Augustine's historic general aviation airport — great views of the oldest airfield in Florida.",
      placeId: "ChIJAe_wm-kp5IgR5OH3g_0TQCE",
    },
    lat: 29.9592,
    lng: -81.3398,
    elevation: 10,
    fuel: "both",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },
  // Georgia
  {
    icao: "KPDK",
    name: "DeKalb-Peachtree Airport",
    state: "GA",
    restaurant: {
      name: "The 57th Fighter Group Restaurant",
      description: "WWII-themed restaurant at Peachtree-DeKalb with authentic warbird décor and a legendary Sunday brunch.",
      placeId: "ChIJc4aS7FsI9YgRhk3Yyqjf9EA",
      website: "https://www.57thfightergroup.com",
    },
    lat: 33.8757,
    lng: -84.3022,
    elevation: 1003,
    fuel: "both",
    hours: "Lunch & dinner, closed Mon",
    runwaySurface: "asphalt",
  },

  // Oregon
  {
    icao: "KSLE",
    name: "McNary Field",
    state: "OR",
    restaurant: {
      name: "Flight Deck Restaurant & Lounge",
      description: "Three-sided windowed restaurant on the Salem ramp with Cascade Mountain views. Full menu from eggs Benedict to the Aviator Tenderloin — great for a weekend breakfast or post-flight dinner.",
      placeId: "ChIJfwpSZLr4v1QRg1phsQCPs3o",
      website: "https://www.facebook.com/FlightDeckRestaurantSalemOR/",
    },
    lat: 44.9095,
    lng: -123.0029,
    elevation: 214,
    fuel: "both",
    hours: "Mon–Fri · lunch & dinner · Sat–Sun from 8am",
    runwaySurface: "asphalt",
  },

  {
    icao: "KBDN",
    name: "Bend Municipal Airport",
    state: "OR",
    restaurant: {
      name: "CJ's at the Airport",
      description: "Casual diner on the Bend Municipal ramp serving breakfast and lunch in the high desert of Central Oregon. Quick stop between the Cascades and the outback — tie down and walk right in.",
      placeId: "ChIJXegEbX3PuFQR3-AbsvmnvbM",
      website: "http://bendairportcafe.com/",
    },
    lat: 44.0932,
    lng: -121.2026,
    elevation: 3460,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },

  // Washington
  {
    icao: "K0S9",
    name: "Jefferson County International",
    state: "WA",
    restaurant: {
      name: "Spruce Goose Cafe",
      description: "Community hub since the 1960s on the Port Townsend peninsula. Known for homemade Marionberry pie and hearty breakfasts; 100LL self-serve available around the clock.",
      placeId: "ChIJK0Fidzjpj1QRG1okVqHYlug",
    },
    lat: 48.0543,
    lng: -122.8106,
    elevation: 108,
    fuel: "100LL",
    hours: "Daily · 8am–4pm",
    runwaySurface: "asphalt",
  },
  {
    icao: "KTIW",
    name: "Tacoma Narrows Airport",
    state: "WA",
    restaurant: {
      name: "The Hub at Gig Harbor",
      description: "Waterfront-inspired grill at Tacoma Narrows with views across the Puget Sound. Burgers, wraps, and Pacific Northwest comfort food — a great stop when exploring the South Sound.",
      placeId: "ChIJWZrkTWerkVQR9Uq9kVvdNtY",
      website: "https://www.thehubgigharbor.com/",
    },
    lat: 47.2678,
    lng: -122.5774,
    elevation: 294,
    fuel: "100LL",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KPWT",
    name: "Bremerton National Airport",
    state: "WA",
    restaurant: {
      name: "Amelia's Hangar",
      description: "Steps from the Bremerton ramp with an outdoor patio overlooking the runway. Full American menu, Sunday brunch, and a kids' playground on site.",
      placeId: "ChIJxbLlWQc1kFQRIU2toUCwxtk",
      website: "https://www.ameliashangar.com",
    },
    lat: 47.4902,
    lng: -122.7645,
    elevation: 444,
    fuel: "both",
    hours: "Tue–Sun · breakfast & dinner",
    runwaySurface: "asphalt",
  },

  // Illinois
  {
    icao: "K06C",
    name: "Schaumburg Regional Airport",
    state: "IL",
    restaurant: {
      name: "Pilot Pete's",
      description: "The gold standard of Midwest fly-in restaurants — packed with aviation memorabilia and panoramic runway windows. Fuel discount offered with a meal purchase.",
      placeId: "ChIJm3jVA1upD4gRGygxv8ljzFo",
      website: "https://www.pilotpetes.com",
    },
    lat: 41.9893,
    lng: -88.1012,
    elevation: 801,
    fuel: "both",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },

  // Colorado
  {
    icao: "KAPA",
    name: "Centennial Airport",
    state: "CO",
    restaurant: {
      name: "The Perfect Landing",
      description: "Upscale continental dining on the second floor of Denver Jet Center with panoramic Rocky Mountain views. Piano bar evenings and one of the highest-elevation airport restaurants in the country.",
      placeId: "ChIJ2W20tvWFbIcRJqaA-AWcuoI",
      website: "https://www.perfectlandingrestaurant.com",
    },
    lat: 39.5702,
    lng: -104.8490,
    elevation: 5883,
    fuel: "both",
    hours: "Daily · breakfast through dinner",
    runwaySurface: "asphalt",
  },
  {
    icao: "KGXY",
    name: "Greeley-Weld County Airport",
    state: "CO",
    restaurant: {
      name: "Captain's Table",
      description: "Breakfast-and-lunch diner in the Greeley GA terminal with direct ramp access. Taxi in, tie down, and walk straight through the door.",
      placeId: "ChIJMyj5qPyZbocRM2YqGGQUZx8",
    },
    lat: 40.4374,
    lng: -104.6330,
    elevation: 4697,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },

  // Kansas
  {
    icao: "KHUT",
    name: "Hutchinson Regional Airport",
    state: "KS",
    restaurant: {
      name: "Airport Steakhouse & Bar",
      description: "Open-hearth charcoal steakhouse steps from the ramp in central Kansas. The 24 oz. Cowboy ribeye is legendary; Sunday brunch buffet draws locals and pilots alike.",
      placeId: "ChIJuVZ6Z-O1pIcRKVRvlloVJL0",
    },
    lat: 38.0665,
    lng: -97.8606,
    elevation: 1543,
    fuel: "both",
    hours: "Mon–Sat · lunch & dinner · Sun brunch",
    runwaySurface: "asphalt",
  },

  // Oklahoma
  {
    icao: "KPNC",
    name: "Ponca City Regional Airport",
    state: "OK",
    restaurant: {
      name: "Enrique's Mexican Restaurant",
      description: "Authentic Mexican food in the terminal with direct ramp views — a true pilots' canteen on the Oklahoma plains. Fajitas and enchiladas are the house favorites.",
      placeId: "ChIJ0_b3cPJfsIcRGWsQjEb0hvU",
    },
    lat: 36.7319,
    lng: -97.1006,
    elevation: 1008,
    fuel: "both",
    hours: "Mon–Sat · lunch & dinner",
    runwaySurface: "asphalt",
  },
  {
    icao: "KADM",
    name: "Ardmore Municipal Airport",
    state: "OK",
    restaurant: {
      name: "Jake's Joint",
      description: "Lunch-only gem with rotating blue-plate specials at Ardmore Municipal. A locals-and-pilots secret in southern Oklahoma — arrive early, it fills up fast.",
      placeId: "ChIJOVdbM8_UTIYRYVG4y4VHcTI",
    },
    lat: 34.3030,
    lng: -97.0197,
    elevation: 777,
    fuel: "both",
    hours: "Mon–Fri · lunch only",
    runwaySurface: "asphalt",
  },

  // Texas
  {
    icao: "T82",
    name: "Gillespie County Airport",
    state: "TX",
    restaurant: {
      name: "Airport Diner",
      description: "1940s chrome diner next to the Hangar Hotel in the Texas Hill Country. Themed menu, retro atmosphere, and overnight rooms on the field — a full weekend destination.",
      placeId: "ChIJYYPFfT_BW4YRfkJHWYVb9cI",
      website: "https://www.hangarhotel.com",
    },
    lat: 30.2429,
    lng: -98.9086,
    elevation: 1695,
    fuel: "both",
    hours: "Wed–Sun · breakfast & lunch",
    runwaySurface: "asphalt",
  },
  {
    icao: "KUVA",
    name: "Garner Field Airport",
    state: "TX",
    restaurant: {
      name: "Hangar 6 Air Cafe",
      description: "Aviation-themed cafe in a converted WWII training hangar with an outdoor patio, playground, and full bar. A perfect stop when crossing south Texas.",
      placeId: "ChIJ8XW0g5T6XoYRmqRxvg3UQAM",
      website: "https://www.hangar6aircafe.com",
    },
    lat: 29.2114,
    lng: -99.7437,
    elevation: 942,
    fuel: "both",
    hours: "Wed–Sat · lunch & dinner",
    runwaySurface: "asphalt",
  },

  // Arizona (additional)
  {
    icao: "KSDL",
    name: "Scottsdale Airport",
    state: "AZ",
    restaurant: {
      name: "Volanti Restaurant & Lounge",
      description: "Upscale global cuisine in the Airport Aviation Business Center with floor-to-ceiling taxiway views. Fine dining with no FBO fee — walk from any ramp on the field.",
      placeId: "ChIJY9xCXH11K4cReAJzrOYJ_bg",
    },
    lat: 33.6229,
    lng: -111.9112,
    elevation: 1510,
    fuel: "both",
    hours: "Tue–Sun · lunch through late",
    runwaySurface: "asphalt",
  },
  {
    icao: "KHII",
    name: "Lake Havasu City Airport",
    state: "AZ",
    restaurant: {
      name: "Hangar 24 Brewery & Grill",
      description: "Craft brewery with an outdoor ramp-view patio in the Sonoran Desert. House-brewed ales, Arizona green chile burgers, and live music most evenings.",
      placeId: "ChIJb6HEdb_v0YAR6tNTlSYfiP4",
    },
    lat: 34.5711,
    lng: -114.3584,
    elevation: 783,
    fuel: "both",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },

  // Arkansas
  {
    icao: "3M0",
    name: "Gaston's Airport",
    state: "AR",
    restaurant: {
      name: "Gaston's Restaurant",
      description: "The original \"Best of the Best\" fly-in resort — a dining room above a 3,200 ft turf strip on the White River. Pan-seared rainbow trout and world-class fly fishing make this a full-weekend destination.",
      placeId: "ChIJgVbqbj8kzocR2LdzsVmGaL0",
      website: "https://www.gastons.com",
    },
    lat: 36.3493,
    lng: -92.5570,
    elevation: 479,
    fuel: "100LL",
    hours: "Daily · breakfast through dinner",
    runwaySurface: "grass",
  },

  // North Carolina
  {
    icao: "5NC3",
    name: "Gilliam-McConnell Airfield",
    state: "NC",
    restaurant: {
      name: "Pik N Pig BBQ",
      description: "Award-winning slow-smoked Carolina BBQ beside a private turf runway in the Sandhills. The pitmaster-owner sometimes pumps 100LL personally for fly-in guests.",
      placeId: "ChIJRe8hzkKsVIgRiocHG1rFwdM",
      website: "https://www.piknpig.com",
    },
    lat: 35.3422,
    lng: -79.4372,
    elevation: 445,
    fuel: "100LL",
    hours: "Thu–Sun · 11am–4pm",
    runwaySurface: "grass",
  },

  // Ohio
  {
    icao: "KPCW",
    name: "Erie-Ottawa International Airport",
    state: "OH",
    restaurant: {
      name: "Tin Goose Diner",
      description: "Restored 1950s O'Mahony stainless diner inside the Liberty Aviation Museum at Port Clinton. Walk in off the ramp, eat classic diner food, and tour WWII warbirds next door.",
      placeId: "ChIJ5-NvNghNOogRsdsop0BHrms",
      website: "https://libertyaviationmuseum.org",
    },
    lat: 41.5163,
    lng: -82.8696,
    elevation: 590,
    fuel: "both",
    hours: "Thu–Mon · breakfast & lunch",
    runwaySurface: "asphalt",
  },

  // Kentucky
  {
    icao: "KLOU",
    name: "Bowman Field",
    state: "KY",
    restaurant: {
      name: "Bistro Le Relais",
      description: "Intimate French bistro in the Art Deco 1940s terminal of one of America's oldest continuously operating airports. Casablanca-inspired décor, classic French cuisine, dinner only.",
      placeId: "ChIJI1iP40YLaYgRd-C9R8rVJLM",
      website: "https://www.lerelaisrestaurant.com",
    },
    lat: 38.2280,
    lng: -85.6637,
    elevation: 546,
    fuel: "both",
    hours: "Dinner Tue–Sun",
    runwaySurface: "asphalt",
  },

  // Pennsylvania
  {
    icao: "KLBE",
    name: "Arnold Palmer Regional Airport",
    state: "PA",
    restaurant: {
      name: "DeNunzio's Italian Chophouse & Sinatra Bar",
      description: "Sinatra-era Italian steakhouse on the second floor with sweeping runway views. Prime-aged steaks, house-made pasta, and a full Sinatra Bar — one of the best fly-in dining rooms in the Northeast.",
      placeId: "ChIJ5YesNxzTNIgRndor29yFNl0",
      website: "https://www.denunzios.com",
    },
    lat: 40.2761,
    lng: -79.4044,
    elevation: 1185,
    fuel: "both",
    hours: "Daily · lunch & dinner",
    runwaySurface: "asphalt",
  },

  // Massachusetts
  {
    icao: "6B6",
    name: "Minute Man Air Field",
    state: "MA",
    restaurant: {
      name: "Fourth & Field",
      description: "Scratch-kitchen cafe and bar at Minute Man Airfield, 25 miles west of Boston. Farm-to-table sandwiches, rotating craft taps, and ramp seating — the modern successor to the beloved Nancy's Airfield Cafe.",
      placeId: "ChIJDXNuhBKT44kRi7hMV4jVWqw",
      website: "https://www.fourthandfield.com",
    },
    lat: 42.4612,
    lng: -71.5188,
    elevation: 268,
    fuel: "100LL",
    hours: "Wed–Sun · breakfast & lunch",
    runwaySurface: "asphalt",
  },

  // Vermont
  {
    icao: "B06",
    name: "Basin Harbor Airport",
    state: "VT",
    restaurant: {
      name: "Red Mill Restaurant",
      description: "Lakeside pub in a converted 19th-century sawmill at the Basin Harbor Resort on Lake Champlain. No fuel on field — plan a fuel stop at Burlington (KBTV, 25 nm). Open late May through mid-October.",
      placeId: "ChIJr91TLhCbykwRbV6egkChBUU",
      website: "https://www.basinharbor.com",
    },
    lat: 44.1915,
    lng: -73.3584,
    elevation: 124,
    fuel: "none",
    hours: "Daily · lunch & dinner (late May–Oct)",
    runwaySurface: "grass",
  },

  // Florida (additional)
  {
    icao: "KFXE",
    name: "Fort Lauderdale Executive Airport",
    state: "FL",
    restaurant: {
      name: "Jet Runway Cafe",
      description: "Runway-side window seating at one of the nation's busiest GA airports. Famous for chicken and waffles and a crab cake hash breakfast while executive jets depart past your table.",
      placeId: "ChIJI_azIOwD2YgRi1gUwP8ggvU",
      website: "https://www.jetrunwaycafe.com",
    },
    lat: 26.1973,
    lng: -80.1707,
    elevation: 13,
    fuel: "both",
    hours: "Daily · breakfast & lunch",
    runwaySurface: "asphalt",
  },
]
